# Project: Progetto1
# Makefile created by Dev-C++ 4.9.8.0

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = Combo_private.res
OBJ  = WinMainStart.o MainWin.o CppProtoWnd.o $(RES)
LINKOBJ  = WinMainStart.o MainWin.o CppProtoWnd.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include/c++/mingw32"  -I"C:/Dev-Cpp/include/c++/backward"  -I"C:/Dev-Cpp/include" 
BIN  = Combo.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS = $(INCS) 

.PHONY: all all-before all-after clean clean-custom

all: all-before Combo.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(LINKOBJ)
	$(CPP) $(LINKOBJ) -o "Combo.exe" $(LIBS)

WinMainStart.o: WinMainStart.cpp
	$(CPP) -c WinMainStart.cpp -o WinMainStart.o $(CXXFLAGS)

MainWin.o: MainWin.cpp
	$(CPP) -c MainWin.cpp -o MainWin.o $(CXXFLAGS)

CppProtoWnd.o: CppProtoWnd.cpp
	$(CPP) -c CppProtoWnd.cpp -o CppProtoWnd.o $(CXXFLAGS)

Combo_private.res: Combo_private.rc resource.rc 
	$(WINDRES) -i Combo_private.rc -I rc -o Combo_private.res -O coff 
