######################################################################
# Automatically generated by qmake (1.07a) Sat Nov 18 20:09:48 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cannon.h lcdrange.h
SOURCES += cannon.cpp lcdrange.cpp main.cpp
