// Class automatically generated by Dev-C++ New Class wizard

#ifndef ACCOPPIATA_H
#define ACCOPPIATA_H

#include "Gioco.h"
#include "Cavallo.h"
#include "Fantino.h"
#include "Contrada.h"
#include "Giocatore.h"
#include "time.h"
#include "stdlib.h"
#include <string>

using namespace std;

class Accoppiata
{
	public:
		Accoppiata();
		~Accoppiata();
		void Set(Cavallo c);
		void Set(Cavallo b, Fantino c);
		string GetCavallo();
		void Avanzamento();
		void Partenza();
		void SetTipoCavallo(int i) { tipoCavallo = i; }
		int IsBono() { return tipoCavallo; }
		void SetStrategia(int i) { strategia = i; }
		int GetStrategia() { return strategia; }
		int GetPosizione() { return posizione; }
		void SetRisultato(int i) { risultato = i; }
		int GetRisultato() { return risultato; }
		bool Rischio(int m);
		
	private:
	    string fantino;
	    string cavallo;
	    int partenza;
	    int caduta;
	    int velocita;
	    int boost;
	    int tipoCavallo;
	    int strategia;
	    int posizione;
	    int risultato;
};

#endif // ACCOPPIATA_H

