# Project: WinTDPalio
# Makefile created by Dev-C++ 4.9.8.0

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = WinTDPalio_private.res
OBJ  = main.o Cavallo.o Contrada.o Corsa.o Fantino.o Giocatore.o Gioco.o tdpalio.o accoppiata.o NewGameDlg.o NewPlayerDlg.o ListDlg.o $(RES)
LINKOBJ  = main.o Cavallo.o Contrada.o Corsa.o Fantino.o Giocatore.o Gioco.o tdpalio.o accoppiata.o NewGameDlg.o NewPlayerDlg.o ListDlg.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include/c++/mingw32"  -I"C:/Dev-Cpp/include/c++/backward"  -I"C:/Dev-Cpp/include" 
BIN  = WinTDPalio.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS = $(INCS) 

.PHONY: all all-before all-after clean clean-custom

all: all-before WinTDPalio.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(LINKOBJ)
	$(CPP) $(LINKOBJ) -o "WinTDPalio.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Cavallo.o: Cavallo.cpp
	$(CPP) -c Cavallo.cpp -o Cavallo.o $(CXXFLAGS)

Contrada.o: Contrada.cpp
	$(CPP) -c Contrada.cpp -o Contrada.o $(CXXFLAGS)

Corsa.o: Corsa.cpp
	$(CPP) -c Corsa.cpp -o Corsa.o $(CXXFLAGS)

Fantino.o: Fantino.cpp
	$(CPP) -c Fantino.cpp -o Fantino.o $(CXXFLAGS)

Giocatore.o: Giocatore.cpp
	$(CPP) -c Giocatore.cpp -o Giocatore.o $(CXXFLAGS)

Gioco.o: Gioco.cpp
	$(CPP) -c Gioco.cpp -o Gioco.o $(CXXFLAGS)

tdpalio.o: tdpalio.cpp
	$(CPP) -c tdpalio.cpp -o tdpalio.o $(CXXFLAGS)

accoppiata.o: accoppiata.cpp
	$(CPP) -c accoppiata.cpp -o accoppiata.o $(CXXFLAGS)

NewGameDlg.o: NewGameDlg.cpp
	$(CPP) -c NewGameDlg.cpp -o NewGameDlg.o $(CXXFLAGS)

NewPlayerDlg.o: NewPlayerDlg.cpp
	$(CPP) -c NewPlayerDlg.cpp -o NewPlayerDlg.o $(CXXFLAGS)

ListDlg.o: ListDlg.cpp
	$(CPP) -c ListDlg.cpp -o ListDlg.o $(CXXFLAGS)

WinTDPalio_private.res: WinTDPalio_private.rc resource.rc 
	$(WINDRES) -i WinTDPalio_private.rc -I rc -o WinTDPalio_private.res -O coff 
