#include <string.h>
#include <bios.h>
#include <stdio.h>
#include <conio.h>
#include <stdlib.h>
#include <ctype.h>
#include <time.h>
#include <graphics.h>
#include <math.h>
#include <dos.h>
#define TRUE 1
#define FALSE 0
#define MAXINT 32767
#define PI 3142
#define TWOPI 6283
#define HALFPI 1571
#define PIANDAHALF 4712
#define NFOOD 3
#define NBLOCK 9
#define NREC 10
#define MAXX 956
#define MINX 0
#define MAXY 902
#define MINY 0
#define sgn(x) ((x<0) ? -1:((x==0) ? 0:1))
#define BLOCKWIDTH 200
#define BLOCKHEIGHT 100
#define PBLOCKWIDTH 100
#define PBLOCKHEIGHT 36
#define MAXENERGY 999
#define ENERGYPERT 625
#define BITEENERGY 250000L
#define PLAYBUG 28501
#define VERSION 1
#define fsgn(x) ((x<0.) ? -1.:((x==0.) ? 0.:1.))
#define MAXREC 200
#define PAUSEINC 2
#define MAXBLK 30






