# Project: Progetto3
# Makefile created by Dev-C++ 4.9.9.1

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  ../../Programmi/MySQL/mysql++-1.7.26/lib/prova.a "../../Programmi/MySQL/MySQL Server 4.1/lib/opt/libmymysql.a"  
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Programmi/MySQL/mysql++-1.7.26/lib"  -I"C:/Programmi/MySQL/MySQL Server 4.1/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include/c++/mingw32"  -I"C:/Dev-Cpp/include/c++/backward"  -I"C:/Dev-Cpp/include"  -I"C:/Programmi/MySQL/mysql++-1.7.26/lib"  -I"C:/Programmi/MySQL/MySQL Server 4.1/include" 
BIN  = Progetto3.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  

.PHONY: all all-before all-after clean clean-custom

all: all-before Progetto3.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Progetto3.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
