######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 8 20:04:31 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
LIBS += -ltdpaliocommon
DESTDIR = ../bin

# Input
HEADERS += tdpalioaiclient.h tdpalioserver.h fase.h
SOURCES += main1.cpp tdpalioaiclient.cpp tdpalioserver.cc fase.cpp
