######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 18 21:57:31 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += led.cpp
