# Project: MiDa
# Makefile created by Dev-C++ 4.9.9.1

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = MiDa_private.res
OBJ  = DB.o main.o Password.o PSheet.o Report.o SearchCD.o SearchClient.o ViewCD.o ViewClient.o ../../Dev-Cpp_5/MiDa/CPanel.o $(RES)
LINKOBJ  = DB.o main.o Password.o PSheet.o Report.o SearchCD.o SearchClient.o ViewCD.o ViewClient.o ../../Dev-Cpp_5/MiDa/CPanel.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows "../../Programmi/MySQL/MySQL Server 4.1/lib/opt/prova.a" "../../Programmi/MySQL/MySQL Server 4.1/lib/opt/libmymysql.a" ../lib/libuser32.a ../lib/libcomdlg32.a ../lib/libgdi32.a ../lib/libcomctl32.a  
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Programmi/MySQL/mysql++-1.7.26/lib"  -I"C:/Programmi/MySQL/MySQL Server 4.1/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include/c++/mingw32"  -I"C:/Dev-Cpp/include/c++/backward"  -I"C:/Dev-Cpp/include"  -I"C:/Programmi/MySQL/mysql++-1.7.26/lib"  -I"C:/Programmi/MySQL/MySQL Server 4.1/include" 
BIN  = MiDa.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  

.PHONY: all all-before all-after clean clean-custom

all: all-before MiDa.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "MiDa.exe" $(LIBS)

DB.o: DB.cc
	$(CPP) -c DB.cc -o DB.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Password.o: Password.cc
	$(CPP) -c Password.cc -o Password.o $(CXXFLAGS)

PSheet.o: PSheet.cc
	$(CPP) -c PSheet.cc -o PSheet.o $(CXXFLAGS)

Report.o: Report.cc
	$(CPP) -c Report.cc -o Report.o $(CXXFLAGS)

SearchCD.o: SearchCD.cc
	$(CPP) -c SearchCD.cc -o SearchCD.o $(CXXFLAGS)

SearchClient.o: SearchClient.cc
	$(CPP) -c SearchClient.cc -o SearchClient.o $(CXXFLAGS)

ViewCD.o: ViewCD.cc
	$(CPP) -c ViewCD.cc -o ViewCD.o $(CXXFLAGS)

ViewClient.o: ViewClient.cc
	$(CPP) -c ViewClient.cc -o ViewClient.o $(CXXFLAGS)

../../Dev-Cpp_5/MiDa/CPanel.o: ../../Dev-Cpp_5/MiDa/CPanel.cc
	$(CPP) -c ../../Dev-Cpp_5/MiDa/CPanel.cc -o ../../Dev-Cpp_5/MiDa/CPanel.o $(CXXFLAGS)

MiDa_private.res: MiDa_private.rc resource.rc 
	$(WINDRES) -i MiDa_private.rc --input-format=rc -o MiDa_private.res -O coff 
