sql_create_19(clienti,1 , 19,
    int, indice,
    string, nome,
    string, cognome,
    string, via1,
    string, citta1,
    string, stato1,
    string, cap1,
    string, nazione1,
    string, via2,
    string, citta2,
    string, stato2,
    string, cap2,
    string, nazione2,
    string, telefono,
    string, cellulare,
    string, email,
    string, carta,
    string, iva,
    string, note);

sql_create_14(cd, 2, 14,    
    int, indice,
    string, artista,
    string, titolo,
    string, etichetta,
    string, formato,
    string, fornitore,
    string, codice,
    float, prezzo_acquisto,
    float, prezzo_vendita,
    float, prezzo_offerta,
    int, stato,
    int, quantita,
    int, prenotazioni,
    int, venduti);    
