######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 31 15:31:28 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bookdelegate.h bookwindow.h initdb.h
SOURCES += bookdelegate.cpp bookwindow.cpp main.cpp
RESOURCES += books.qrc
