TYPE Contrada
    nome AS STRING * 10
    avversaria AS STRING * 10
    popolo AS INTEGER
    vittorie AS INTEGER
    astinenza AS INTEGER
END TYPE

TYPE Cavallo
    nome AS STRING * 15
    vittorie AS INTEGER
    corsi AS INTEGER
    spunto AS INTEGER
    velocita AS INTEGER
    resistenza AS INTEGER
END TYPE

TYPE Fantino
    nome AS STRING * 10
    vittorie AS INTEGER
    corsi AS INTEGER
    prontezza AS INTEGER
    abilita AS INTEGER
    coraggio AS INTEGER
END TYPE



