######################################################################
# Automatically generated by qmake (1.07a) Sun May 6 13:09:44 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += brace.ui.h braciere.ui.h oggetti.h subprenotazioni.h tavolo.ui.h
INTERFACES += brace.ui braciere.ui prenotazioni.ui sistemazione.ui tavolo.ui
SOURCES += main.cpp oggetti.cpp qmake_image_collection.cpp subprenotazioni.cpp
