######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 31 17:26:34 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += combgen.h prenotazioni.h
SOURCES += combination.cpp prenotazioni.cpp
