######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 18 22:41:51 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
