######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 19 02:39:51 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += InsertPlayerDialog.h InsertPlayerModel.h punti.h segnapunti.h
FORMS += insertplayer.ui segnapunti.ui tabellone.ui
SOURCES += InsertPlayerDialog.cpp InsertPlayerModel.cpp main.cpp punti.cpp
