######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 1 11:59:27 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
