# Project: teaMaker
# Makefile created by Dev-C++ 4.9.9.1

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = teaMaker_private.res
OBJ  = main.o giocatore.o combinazioni.o formazioni.o $(RES)
LINKOBJ  = main.o giocatore.o combinazioni.o formazioni.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -L"C:/Dev-Cpp_5/lib" ../lib/libcomctl32.a  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include/c++/mingw32"  -I"C:/Dev-Cpp/include/c++/backward"  -I"C:/Dev-Cpp/include" 
BIN  = teaMaker.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  

.PHONY: all all-before all-after clean clean-custom

all: all-before teaMaker.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "teaMaker.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

giocatore.o: giocatore.cc
	$(CPP) -c giocatore.cc -o giocatore.o $(CXXFLAGS)

combinazioni.o: combinazioni.cc
	$(CPP) -c combinazioni.cc -o combinazioni.o $(CXXFLAGS)

formazioni.o: formazioni.cc
	$(CPP) -c formazioni.cc -o formazioni.o $(CXXFLAGS)

teaMaker_private.res: teaMaker_private.rc resource.rc 
	$(WINDRES) -i teaMaker_private.rc --input-format=rc -o teaMaker_private.res -O coff 
