######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 11 00:28:41 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += animateditem.h ledmeter.h sprites.h toplevel.h view.h
SOURCES += animateditem.cpp ledmeter.cpp main.cpp toplevel.cpp view.cpp
RESOURCES += portedasteroids.qrc
