######################################################################
# Automatically generated by qmake (2.01a) Tue May 20 00:54:15 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
