# Project: Palio
# Makefile created by Dev-C++ 4.9.9.1

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = Palio_private.res
OBJ  = main.o Gioco.o NewGameDlg.o Giocatore.o Utilities.o Contrada.o Gioco_bis.o $(RES)
LINKOBJ  = main.o Gioco.o NewGameDlg.o Giocatore.o Utilities.o Contrada.o Gioco_bis.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include/c++/mingw32"  -I"C:/Dev-Cpp/include/c++/backward"  -I"C:/Dev-Cpp/include" 
BIN  = Palio.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  

.PHONY: all all-before all-after clean clean-custom

all: all-before Palio.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Palio.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Gioco.o: Gioco.cc
	$(CPP) -c Gioco.cc -o Gioco.o $(CXXFLAGS)

NewGameDlg.o: NewGameDlg.cc
	$(CPP) -c NewGameDlg.cc -o NewGameDlg.o $(CXXFLAGS)

Giocatore.o: Giocatore.cpp
	$(CPP) -c Giocatore.cpp -o Giocatore.o $(CXXFLAGS)

Utilities.o: Utilities.cc
	$(CPP) -c Utilities.cc -o Utilities.o $(CXXFLAGS)

Contrada.o: Contrada.cpp
	$(CPP) -c Contrada.cpp -o Contrada.o $(CXXFLAGS)

Gioco_bis.o: Gioco_bis.cc
	$(CPP) -c Gioco_bis.cc -o Gioco_bis.o $(CXXFLAGS)

Palio_private.res: Palio_private.rc resource.rc 
	$(WINDRES) -i Palio_private.rc --input-format=rc -o Palio_private.res -O coff 
