######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 14 13:14:36 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stardelegate.h stareditor.h starrating.h
SOURCES += main.cpp stardelegate.cpp stareditor.cpp starrating.cpp
