// Class automatically generated by Dev-C++ New Class wizard

#include "accoppiata.h"

Accoppiata::Accoppiata()
{
    fantino = "";
    cavallo = "";
    partenza = 0;
    caduta = 0;
    velocita = 0;
    boost = 0;
    tipoCavallo = -1;
    strategia = -1;
    risultato = 0;
    posizione = 0;
}

Accoppiata::~Accoppiata()
{
}

void Accoppiata::Set(Cavallo c)
{
    cavallo = c.GetNome();
    fantino = "Comunale";
    partenza = (c.GetProntezza() + 6);
    caduta = (c.GetPrecisione() + 6)/2;
    velocita = c.GetVelocita();
    boost = c.GetResistenza();
    posizione = 0;
    risultato = 0;
}    

void Accoppiata::Set(Cavallo c, Fantino f)
{
    partenza = (c.GetProntezza() + f.GetProntezza());
    caduta = (c.GetPrecisione() + f.GetRischio())/2;
    velocita = c.GetVelocita();
    boost = c.GetResistenza();
    posizione = 0;
    risultato = 0;
}    

void Accoppiata::Partenza()
{
   int mossa = 0;
   srand(time(NULL));
   mossa =  partenza - (rand() % 5);
   
   posizione += mossa;
}

bool Accoppiata::Rischio(int mossa)
{
    int c = caduta;
    if (mossa < 4)
        c += 5;
    if ((mossa < 6) && (mossa > 3))
        c += 3;
    
    srand(time(NULL));    
    
    if ((rand() % 10) > c)
        return true;
    else 
        return false;         
}

void Accoppiata::Avanzamento()
{
    srand(time(NULL));    
    
    int mossa = (rand() % velocita) + 1;
    if ((mossa < 5) && (boost > 50))
    {
        boost -= 1;
        mossa += 2;
    }
    
    if ((mossa > 1) && (boost == 0))
        mossa -= 1;
    
    if ((mossa < 5) && (boost > 0) && (boost < 51))
        boost -= 1;

    posizione += mossa;    
}

string Accoppiata::GetCavallo()
{
    return cavallo;
}



