######################################################################
# Automatically generated by qmake (1.07a) Tue Aug 28 17:52:45 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += canvas.h
SOURCES += canvas.cpp main.cpp
