######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 20 22:12:03 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mouse.h engine.h
SOURCES += main.cpp mouse.cpp engine.cc
RESOURCES += mice.qrc
